name: sportsapp
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash-logo.png
    - assets/images/branding.png

