// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaUPPmAfh-u28JarHCIRJOsFxl-qZ8ydE',
    appId: '1:336752803795:web:a63686459f5fe3e331f926',
    messagingSenderId: '336752803795',
    projectId: 'sportsapp-3edf8',
    authDomain: 'sportsapp-3edf8.firebaseapp.com',
    storageBucket: 'sportsapp-3edf8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcol3TIm6ZtZuJwPEUXXQuuqr9dkn7K6o',
    appId: '1:336752803795:android:150cd125fe16190231f926',
    messagingSenderId: '336752803795',
    projectId: 'sportsapp-3edf8',
    storageBucket: 'sportsapp-3edf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLLm2KS0pGqUW6_E7LWo8iVHNcYnmC2g',
    appId: '1:336752803795:ios:852fabcb41600b1331f926',
    messagingSenderId: '336752803795',
    projectId: 'sportsapp-3edf8',
    storageBucket: 'sportsapp-3edf8.firebasestorage.app',
    iosBundleId: 'com.example.sportsapp',
  );

}